name: Build Windows (Cross Compile)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [synchronize, opened, reopened, ready_for_review]
  workflow_dispatch:

concurrency: 
  group: build-win-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install flex bison mingw-w64-x86-64-dev mingw-w64-tools g++-mingw-w64-x86-64
    
    - name: Setup Dependency
      run: | 
        TARGET=x86_64-w64-mingw32
        ADDRM=64
        MTUNE=generic

        CORES=$(nproc || 1)

        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++

        export PREFIX=$(pwd)/prefixDepend 
        #export PREFIX=$(realpath $PREFIX)
        mkdir -p $PREFIX
        
        BOOST=boost_1_72_0
        VER=${BOOST#boost_}
        VER=${VER//_/.}
        
        wget -nv "https://boostorg.jfrog.io/artifactory/main/release/$VER/source/$BOOST.tar.bz2"
        tar xf $BOOST.tar.bz2

        cd $BOOST
        CC= CXX= ./bootstrap.sh --prefix="$PREFIX" --without-icu
        cat > win$ADDRM-config.jam << EOF
        using gcc : m : $CXX
                :
        ;
        EOF

        ./b2 toolset=gcc-m target-os=windows cflags="-mtune=$MTUNE" cxxstd=17 cxxflags="-mtune=$MTUNE" address-model="$ADDRM" binary-format="pe" abi="ms" threading="multi" threadapi="win32" variant=release --user-config="win$ADDRM-config.jam" --prefix="$PREFIX" --without-mpi --without-python --without-coroutine --without-graph --without-graph_parallel --without-wave --without-context -sNO_BZIP2=1 -j$CORES install
        cd ..

        sudo apt install unzip
        wget https://github.com/sparsehash/sparsehash/archive/sparsehash-2.0.4.zip
        unzip sparsehash-2.0.4.zip
        cd sparsehash-sparsehash-2.0.4
        ./configure CXXFLAGS=-std=c++11 --prefix="$PREFIX" --host win
        make
        make install
        cd ..
        
        
    - name: Build 
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeAppendedArgs: >-
          -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/verifytapn/toolchain-x86_64-w64-mingw32.cmake
          -DBOOST_ROOT=${{runner.workspace}}/verifytapn/prefixDepend
          -DBoost_INCLUDE_DIR=${{runner.workspace}}/verifytapn/prefixDepend/include
        cmakeBuildType: Release
        cmakeGenerator: UnixMakefiles
        buildDirectory: '${{runner.workspace}}/build'     
    
    - name: Upload artifacts 
      uses: actions/upload-artifact@v2
      with:
        name: verifytapn-win64
        path: '${{runner.workspace}}/build/verifytapn/bin/verifytapn-win64.exe'
