# This is a basic workflow to help you get started with Actions

name: Build Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: ubuntu install depends
      run: |
        sudo apt-get install -f flex bison libboost-all-dev libsparsehash-dev cmake build-essential

    - name: Build 
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtBasic
        cmakeAppendedArgs: ''
        cmakeBuildType: Release
        cmakeGenerator: UnixMakefiles
        buildDirectory: '${{runner.workspace}}/build'     

    - name: Upload artifacts 
      uses: actions/upload-artifact@v2
      with:
        name: verifytapn-linux64
        path: '${{runner.workspace}}/build/bin/verifytapn-linux64'
